package com.zappos.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.zappos.marshalling.RouterDescriptionTypeConverter;

import java.util.Map;

/**
 * A {@code RouterSignature} is a snapshot of all wireless networks within the range of the host device at the time of
 * sampling.
 */
@DynamoDBTable(tableName = "router-signatures")
public class RouterSignature {
    /**
     * UUID for this signature.
     */
    private String id;

    /**
     * The host that this {@code RouterSignature} belongs to.
     */
    private String hostname;

    /**
     * A timestamp for this request
     */
    private String timestamp;

    /**
     * {@code Map} of BSSID -> {@code RouterDescription} for each visible network at time of sampling.
     */
    private Map<String, Router> routers;


    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBIndexHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }
    public void setId(String uuid) {
        this.id = uuid;
    }

    @DynamoDBRangeKey(attributeName = "hostname")
    public String getHostname() {
        return hostname;
    }
    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    @DynamoDBIndexRangeKey(attributeName = "timestamp")
    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    @DynamoDBMarshalling(marshallerClass = RouterDescriptionTypeConverter.class)
    public Map<String, Router> getRouters() {
        return routers;
    }

    public void setRouters(Map<String, Router> routers) {
        this.routers = routers;
    }

    @Override
    public String toString() {
        return "LocationProfile{" +
                "id='" + id + '\'' +
                ", routers=" + routers +
                '}';
    }
}
