package com.zappos.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.zappos.marshalling.LocationTypeConverter;
import com.zappos.marshalling.RouterSignatureTypeConverter;

/**
 * This class decorates the normal RouterSignature with some extra goodies
 */
@DynamoDBTable(tableName = "training-sets")
public class TrainingSignature {

    /**
     * Uuid for this signature
     */
    private String id;

    private String version;

    private Location location;

    /**
     * This X-coordinate for this {@code TrainingSignature}. These are added just in case.
     */
    private Double x;

    private Double y;

    private Double floor;

    /**
     * The {@link com.zappos.model.RouterSignature} for this training point.
     */
    private RouterSignature routerSignature;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey
    public String getVersion() {
        return version;
    }
    public void setVersion(String version) {
        this.version = version;
    }

    @DynamoDBMarshalling(marshallerClass = LocationTypeConverter.class)
    public Location getLocation() {
        return location;
    }
    public void setLocation(Location location) {
        this.location = location;
    }

    @DynamoDBAttribute
    public Double getX() {
        return x;
    }
    public void setX(Double x) {
        this.x = x;
    }

    @DynamoDBAttribute
    public Double getY() {
        return y;
    }
    public void setY(Double y) {
        this.y = y;
    }

    @DynamoDBAttribute
    public Double getFloor() {
        return floor;
    }
    public void setFloor(Double floor) {
        this.floor = floor;
    }

    @DynamoDBMarshalling(marshallerClass = RouterSignatureTypeConverter.class)
    public RouterSignature getRouterSignature() {
        return routerSignature;
    }

    public void setRouterSignature(RouterSignature routerSignature) {
        this.routerSignature = routerSignature;
    }
}
